ci tests verbosity

diff --git a/.gitea/workflows/ci.yml b/.gitea/workflows/ci.yml
--- a/.gitea/workflows/ci.yml
+++ b/.gitea/workflows/ci.yml
@@ -23,7 +23,7 @@ jobs:
           pip freeze
       - name: Migrate DB
         run: |
-          source venv/bin/activate && \
+          source venv/bin/activate
           python3 fsthub/manage.py migrate || { echo "Migration failed"; exit 1; }
           DJANGO_SUPERUSER_USERNAME=TEST \
           DJANGO_SUPERUSER_PASSWORD=TEST \
@@ -45,6 +45,9 @@ jobs:
           pkill python
       - name: Run tests
         run: |
-          source venv/bin/activate && \
-          source .env && \
-          python3 fsthub/manage.py test fsthub || { echo "Tests failed"; exit 1; }
+          echo "Activating environment"
+          source venv/bin/activate
+          source .env
+          echo "Running tests"
+          python3 fsthub/manage.py test fsthub --verbosity=2 --no-input || \
+          { echo "Tests failed"; exit 1; }
