ci paths updated

diff --git a/.gitea/workflows/ci.yml b/.gitea/workflows/ci.yml
--- a/.gitea/workflows/ci.yml
+++ b/.gitea/workflows/ci.yml
@@ -23,11 +23,12 @@ jobs:
           pip freeze
       - name: Migrate DB
         run: |
-          source venv/bin/activate && python3 src/manage.py migrate || { echo "Migration failed"; exit 1; }
+          source venv/bin/activate && cd fsthub && \
+          python3 fsthub/manage.py migrate || { echo "Migration failed"; exit 1; }
           DJANGO_SUPERUSER_USERNAME=TEST \
           DJANGO_SUPERUSER_PASSWORD=TEST \
           DJANGO_SUPERUSER_EMAIL="test@example.com" \
-          python3 src/manage.py createsuperuser --noinput || { echo "Creation failed"; exit 1; }
+          python3 fsthub/manage.py createsuperuser --noinput || { echo "Creation failed"; exit 1; }
       - name: Check development status code
         run: |
           echo "Activating environment"
@@ -35,7 +36,7 @@ jobs:
           source venv/bin/activate
           source .env
           echo "Starting up the development server"
-          python3 src/manage.py runserver localhost:8000 --noreload > /dev/null 2>&1 & sleep 10
+          python3 fsthub/manage.py runserver localhost:8000 --noreload > /dev/null 2>&1 & sleep 10
           echo "Calling the development server"
           source .env
           RESP=$(curl -fsSIm 1 http://localhost:8000/$FSTHUB_PREFIX | head -n 1)
