CI ssh test

diff --git a/.gitea/workflows/ci.yml b/.gitea/workflows/ci.yml
--- a/.gitea/workflows/ci.yml
+++ b/.gitea/workflows/ci.yml
@@ -9,53 +9,56 @@ jobs:
       - uses: webfactory/ssh-agent@v0.9.1
         with:
             ssh-private-key: ${{ secrets.FSTHUB_SSH_PK }}
+      - name: Test ssh command
+        run: ssh fsthub@lingconlab.ru "ls -a"
   
-  test-dev-app:
-    name: Test the development app
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup python
-        run: |
-          apt update && apt upgrade -y
-          apt install -y python3 python3-pip python3-venv
-          apt install -y gcc python3-dev
-          apt install -y hfst
-          python3 --version && pip3 --version
-      - name: Install python dependencies
-        if: steps.cache-venv.outputs.cache-hit != 'true'
-        run: |
-          python3 -m venv venv
-          source venv/bin/activate
-          pip install -r requirements.txt
-          pip freeze
-      - name: Migrate DB
-        run: |
-          source venv/bin/activate
-          python3 fsthub/manage.py migrate || { echo "Migration failed"; exit 1; }
-          DJANGO_SUPERUSER_USERNAME=TEST \
-          DJANGO_SUPERUSER_PASSWORD=TEST \
-          DJANGO_SUPERUSER_EMAIL="test@example.com" \
-          python3 fsthub/manage.py createsuperuser --noinput || { echo "Creation failed"; exit 1; }
-      - name: Check development status code
-        run: |
-          echo "Activating environment"
-          set -eEuo pipefail
-          source venv/bin/activate
-          source .env
-          echo "Starting up the development server"
-          python3 fsthub/manage.py runserver localhost:8000 --noreload > /dev/null 2>&1 & sleep 10
-          echo "Calling the development server"
-          source .env
-          RESP=$(curl -fsSIm 1 http://localhost:8000/$FSTHUB_PREFIX | head -n 1)
-          echo "Server response: $RESP"
-          test $(echo $RESP | awk '{print $2}') = 200
-          pkill python
-      - name: Run tests
-        run: |
-          echo "Activating environment"
-          source venv/bin/activate
-          source .env
-          echo "Running tests"
-          python3 fsthub/manage.py test fsthub --verbosity=2 --no-input || \
-          { echo "Tests failed"; exit 1; }
+  #test-dev-app:
+  #  name: Test the development app
+  #  runs-on: ubuntu-22.04
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #    - name: Setup python
+  #      run: |
+  #        apt update && apt upgrade -y
+  #        apt install -y python3 python3-pip python3-venv
+  #        apt install -y gcc python3-dev
+  #        apt install -y hfst
+  #        python3 --version && pip3 --version
+  #    - name: Install python dependencies
+  #      if: steps.cache-venv.outputs.cache-hit != 'true'
+  #      run: |
+  #        python3 -m venv venv
+  #        source venv/bin/activate
+  #        pip install -r requirements.txt
+  #        pip freeze
+  #    - name: Migrate DB
+  #      run: |
+  #        source venv/bin/activate
+  #        python3 fsthub/manage.py migrate || { echo "Migration failed"; exit 1; }
+  #        DJANGO_SUPERUSER_USERNAME=TEST \
+  #        DJANGO_SUPERUSER_PASSWORD=TEST \
+  #        DJANGO_SUPERUSER_EMAIL="test@example.com" \
+  #        python3 fsthub/manage.py createsuperuser --noinput || { echo "Creation failed"; exit 1; }
+  #    - name: Check development status code
+  #      run: |
+  #        echo "Activating environment"
+  #        set -eEuo pipefail
+  #        source venv/bin/activate
+  #        source .env
+  #        echo "Starting up the development server"
+  #        python3 fsthub/manage.py runserver localhost:8000 --noreload > /dev/null 2>&1 & sleep 10
+  #        echo "Calling the development server"
+  #        source .env
+  #        RESP=$(curl -fsSIm 1 http://localhost:8000/$FSTHUB_PREFIX | head -n 1)
+  #        echo "Server response: $RESP"
+  #        test $(echo $RESP | awk '{print $2}') = 200
+  #        pkill python
+  #    - name: Run tests
+  #      run: |
+  #        echo "Activating environment"
+  #        source venv/bin/activate
+  #        source .env
+  #        echo "Running tests"
+  #        python3 fsthub/manage.py test fsthub --verbosity=2 --no-input || \
+  #        { echo "Tests failed"; exit 1; }
+#
